openapi: 3.0.0
info:
  title: Dashboard Management API
  description: API for user authentication, dashboard and chart management.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
paths:
  /auth/signup:
    post:
      summary: Sign up a new user
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - name
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "user created successfully with id: 1"
        '400':
          description: Bad request (invalid parameters)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid data provided"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Database error"

  /auth/login:
    post:
      summary: Login a user
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful, returns user details and JWT token in cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      username:
                        type: string
                        example: "johndoe"
                      email:
                        type: string
                        example: "john.doe@example.com"
                      name:
                        type: string
                        example: "John Doe"
        '400':
          description: Invalid credentials or bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid username or password"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Error generating token"

  /dashboards:
    get:
      summary: Retrieve a list of dashboards
      operationId: getDashboards
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of dashboards
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: "Sales Dashboard"
                        charts_count:
                          type: integer
                          example: 3
        '401':
          description: Unauthorized access (missing or invalid token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unauthorized"

  /dashboards:
    post:
      summary: Create a new dashboard
      operationId: createDashboard
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '201':
          description: Dashboard created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Dashboard created with ID: 1"
        '400':
          description: Bad request (invalid data)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid dashboard data"
        '401':
          description: Unauthorized access (missing or invalid token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unauthorized"

  /dashboards/{dashboardId}:
    put:
      summary: Update the name of an existing dashboard
      operationId: updateDashboard
      security:
        - cookieAuth: []
      parameters:
        - name: dashboardId
          in: path
          required: true
          description: The ID of the dashboard to update
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Dashboard updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Dashboard name updated successfully!"
        '400':
          description: Invalid data provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid name"
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unauthorized"
        '404':
          description: Dashboard not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Dashboard not found"

  /dashboards/{dashboardId}:
    get:
      summary: Get a specific dashboard by ID
      operationId: getDashboardById
      security:
        - cookieAuth: []
      parameters:
        - name: dashboardId
          in: path
          required: true
          description: The ID of the dashboard to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Dashboard details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "Sales Dashboard"
                      charts:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            type:
                              type: string
                              example: "bar"
                            data:
                              type: string
                              example: '{"x": [1,2,3], "y": [3,2,1]}'
        '401':
          description: Unauthorized access (missing or invalid token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unauthorized"
        '404':
          description: Dashboard not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Dashboard not found"

  /dashboards/{dashboardId}/charts:
    post:
      summary: Add a chart to a dashboard
      operationId: addChart
      security:
        - cookieAuth: []
      parameters:
        - name: dashboardId
          in: path
          required: true
          description: The ID of the dashboard to add the chart to
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: "bar"
                data:
                  type: string
                  example: '{"x": [1, 2, 3], "y": [3, 2, 1]}'
      responses:
        '201':
          description: Chart added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Chart added with ID: 1"
        '400':
          description: Invalid chart data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid chart data"
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unauthorized"

security:
  - cookieAuth: []

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
